### ISSUE TITLE
Break out additional settings

### ISSUE THREAD

**Issue by Ambrosiani** [NordicMuseum/Wikimedia-Commons-uploads#10]
Settings that need to move from scripts to the `settings.json` file:

from DiMuMappingUpdater.py:
- options (line 423–440)

from make_NordicMuseum_info.py
- MAPPINGS_DIR (line 25)
- BATCH_CAT (line 26)
- BATCH_DATE (line 27)
- LOGFILE (line 28)
- self.bad_names (line 45)
- self.bad_dates (line 46)
- load_mapping_lists (line 76)
- 'Nordiska museet' (line 120)
- template_data['institution'] (line 168, 195)
- glam (line 373)
- Nordiska museet description (line 406)
- Nordiska museet link (line 411)
- Nordiska museet (line 419)
- Nordiska museet cooperation project (line 424)

**Comment by Abbe98** [comment]
Could we use some type of wikitext template file in which one would add upload/institution specific Wikitext?

Could be appended upon generated wikitext or entirely driven by variables such as it's done in Pattypan (https://github.com/yarl/pattypan/blob/master/src/pattypan/Settings.java#L114).

**Comment by Ambrosiani** [comment]
these are the current ones used in the Artwork template. Most of them are already pulled from the harvested metadata.

```
        template_name = 'Artwork'
        template_data = OrderedDict()
        template_data['artist'] = item.get_creator()
        template_data['title'] = item.get_title()
        template_data['date'] = item.get_creation_date()
        template_data['description'] = item.get_description(with_depicted=True)
        template_data['other_fields_2'] = item.get_original_description()
        template_data['medium'] = item.get_materials()
        template_data['dimensions'] = ''
        template_data['institution'] = '{{Institution:Nordiska museet}}'
        template_data['location'] = ''
        template_data['references'] = ''
        template_data['object history'] = ''
        template_data['credit line'] = ''
        template_data['inscriptions'] = item.get_inscriptions()
        template_data['notes'] = ''
        template_data['accession number'] = item.get_id_link()
        template_data['source'] = item.get_source()
        template_data['permission'] = item.get_license_text()
        template_data['other_versions'] = item.get_other_versions()
```

I think adding some additional variables (like institution) and then pulling the values from a settings file is the intuitive way to do it.

**Comment by Vesihiisi** [comment]
Addressed in https://github.com/NordicMuseum/Wikimedia-Commons-uploads/pull/23
