### ISSUE TITLE
Separate institution & batch settings

### ISSUE THREAD

**Issue by Ambrosiani** [NordicMuseum/Wikimedia-Commons-uploads#11]
It would be nice to separate institution settings (consistent across batches) and specific batch settings into two different files. Currently [settings.json](https://github.com/NordicMuseum/Wikimedia-Commons-uploads/blob/master/settings.example.json) handles all settings.

**Comment by Vesihiisi** [comment]
Addressed in https://github.com/NordicMuseum/Wikimedia-Commons-uploads/pull/23
