### ISSUE TITLE
Fetch institution name from API

### ISSUE THREAD

**Issue by Ambrosiani** [NordicMuseum/Wikimedia-Commons-uploads#13]
Using the institution code (example: S-NM for Nordiska museet), institution names can be fetched from [owners](http://api.dimu.org/api/owners?country=se&api.key=demo) (in XML format)

**Comment by Vesihiisi** [comment]
Didn't implement this in the end, as it wasn't clear where it would actually be useful. The name of the "Images from {institution}" category was a candidate, but I think it makes more sense to be able to input it manually. It's a minor thing and I can imagine situations where you'd want a category name slightly different than the official name of the institution, especially if that category already exists on Commons.

**Comment by Ambrosiani** [comment]
agree completely!
