### ISSUE TITLE
Separate creator from license

### ISSUE THREAD

**Issue by lokal-profil** [NordicMuseum/Wikimedia-Commons-uploads#15]
The creator appears in various different places depending on type (see below). Breaking it out as it's own top_level harvested data would go a long way in unifying these.

Be aware of more complicated cases e.g. photographer and depicted artwork creator.

**Comment by Ambrosiani** [comment]
So far we've identified three different cases:

1. A scan of an artwork. artifactType is "Photograph" but there's no `eventWrap.events[0].eventType` "fotografering". In this case, creator is available at `licenses[0].persons[0].uuid`. Example: [Boberg drawing](http://api.dimu.org/artifact/uuid/5456EB9D-4B10-4C98-849A-7952EFD22A6D)
2. A photo from the photo collections. artifactType is "Photograph" and there's an `eventWrap.events[0].eventType` "fotografering". In this case, creator can be fetched from `eventWrap.events[0].relatedPersons[0].uuid`. Not implemented yet. Example: [Holmén fashion photo](http://api.dimu.org/artifact/uuid/885D025B-FC85-4D45-924E-BF0030BE47D0)
3. A photo of an item. artifactType is "Thing" and there's no `eventWrap.events[0].eventType` "fotografering". In this case, the photographer is fetched from `media.pictures[0].photographer` and there's no uuid, only name. Example: [Eriksson photo of a package of nylon stockings](http://api.dimu.org/artifact/uuid/3E26AF60-983C-424F-8BB2-00000AD71A3E)

**Comment by Vesihiisi** [comment]
Addressed in https://github.com/NordicMuseum/Wikimedia-Commons-uploads/pull/23
