### ISSUE TITLE
Handle slide ids

### ISSUE THREAD

**Issue by Ambrosiani** [NordicMuseum/Wikimedia-Commons-uploads#19]
Add slide id as a parameter in the harvest file.
Add setting to only harvest the first slide of objects.

(slides are harvested in function process_single_object in DiMuHarvester.py)

**Comment by Vesihiisi** [comment]
i'm suddenly having flashbacks to lots of back sides of paintings

**Comment by Vesihiisi** [comment]
Addressed in https://github.com/NordicMuseum/Wikimedia-Commons-uploads/pull/23
