### ISSUE TITLE
handle 2D artworks, objects & photos

### ISSUE THREAD

**Issue by Ambrosiani** [NordicMuseum/Wikimedia-Commons-uploads#20]
Three object types are present in the Nordic Museum collections (there are additional ones in Digitalt museum but let's start with the Nordic Museum ones):

1. A scan of a two-dimensional artwork. **Done.**
uses {{Artwork}} template.
artifactType is "Photograph" but there's no `eventWrap.events[0].eventType` "fotografering". 
Part of the NMA (Nordiska museets arkiv) collection. 
Example: [Boberg drawing](http://api.dimu.org/artifact/uuid/5456EB9D-4B10-4C98-849A-7952EFD22A6D). 

2. A photo from the photo collections. **Not implemented yet.** 
uses {{Photograph}} or {{Artwork}} template.
artifactType is "Photograph" and there's an `eventWrap.events[0].eventType` "fotografering". 
Part of the NMA (Nordiska museets arkiv) collection. 
Example: [Holmén fashion photo](http://api.dimu.org/artifact/uuid/885D025B-FC85-4D45-924E-BF0030BE47D0).

3. An object. **Not implemented yet.**
uses {{Photograph}} template.
artifactType is "Thing". There's no `eventWrap.events[0].eventType` "fotografering" – instead, the photo specific info is in the `media.pictures[]` array. 
Part of the NM (Nordiska museets föremålssamling) collection. 
Example: [Eriksson photo of a package of nylon stockings](http://api.dimu.org/artifact/uuid/3E26AF60-983C-424F-8BB2-00000AD71A3E).

**Comment by Vesihiisi** [comment]
Addressed in https://github.com/NordicMuseum/Wikimedia-Commons-uploads/pull/23
