### ISSUE TITLE
add cache step in harvester?

### ISSUE THREAD

**Issue by Ambrosiani** [NordicMuseum/Wikimedia-Commons-uploads#30]
the script would be more robust if a cache step was made before creating the harvest file, i.e. if the API request was saved in a local json. That way, manual data corrections can be made without having to wait for Digitalt museum to import changes in Primus.

**Comment by Vesihiisi** [comment]
I approve of this very much.

**Comment by Ambrosiani** [comment]
also, sorting the harvest (by uuid or something else) would be nice since DiMu returns results in random order.

**Comment by Vesihiisi** [comment]
yeeeah the order is confusing. I find the idea of sorting by a random identifier amazing, but at least we'd get a _consistent_ random order 😂 Maybe identifier[id] would be better....

**Comment by Vesihiisi** [comment]
Dumping some thoughts…

Here's the glam_ids of the first 10 results when harvesting

```
[('S-NM', 'NM.0014332B')]
[('S-NM', 'NM.0014332A')]
[('S-NM', 'NM.0014331A')]
[('S-NM', 'NM.0014331B')]
[('S-NM', 'NM.0015736B')]
[('S-NM', 'NM.0017158A')]
[('S-NM', 'NM.0018168A')]
[('S-NM', 'NM.0018168B')]
[('S-NM', 'NM.0019763B')]
[('S-NM', 'NM.0019763B')]
[('S-NM', 'NM.0019766')]
```

The order is consistent – I get the same result on several harvester runs. This means the DiMu response is not actually random (or maybe it's just cached! and it will be different tomorrow!)

It's also _almost_ sorted, but not quite… 0014332 comes before 0014331. And it's only the top couple results, so it might be a total mess further down there for all I know.

**Comment by Vesihiisi** [comment]
And after sorting by glam code it would look like this... So I'm gonna run this sort before saving the harvest file :)

```
[('S-NM', 'NM.0014331A')]
[('S-NM', 'NM.0014331B')]
[('S-NM', 'NM.0014332A')]
[('S-NM', 'NM.0014332B')]
[('S-NM', 'NM.0015736B')]
[('S-NM', 'NM.0017158A')]
[('S-NM', 'NM.0018168A')]
[('S-NM', 'NM.0018168B')]
[('S-NM', 'NM.0019763B')]
[('S-NM', 'NM.0019763B')]
[('S-NM', 'NM.0019766')]
```

**Comment by Ambrosiani** [comment]
🙌

12 dec. 2018 kl. 12:40 skrev Alicia Fagerving <notifications@github.com<mailto:notifications@github.com>>:


And after sorting by glam code it would look like this... So I'm gonna run this sort before saving the harvest file :)

[('S-NM', 'NM.0014331A')]
[('S-NM', 'NM.0014331B')]
[('S-NM', 'NM.0014332A')]
[('S-NM', 'NM.0014332B')]
[('S-NM', 'NM.0015736B')]
[('S-NM', 'NM.0017158A')]
[('S-NM', 'NM.0018168A')]
[('S-NM', 'NM.0018168B')]
[('S-NM', 'NM.0019763B')]
[('S-NM', 'NM.0019763B')]
[('S-NM', 'NM.0019766')]
