### ISSUE TITLE
Handle artifact type "Thing" in DiMuHarvester.py

### ISSUE THREAD

**Issue by Ambrosiani** [NordicMuseum/Wikimedia-Commons-uploads#9]
Right now only artifact types "Folder" and "Photograph" are handled. "Thing" has a different metadata structure and any folder containing Things throws an error.

Artifact type is fetched from the Digitalt Museum API using the property `artifact.type`.

**Comment by Ambrosiani** [comment]
after today's updates, Things are now throwing errors in the log instead of crashing the script.

**Comment by Vesihiisi** [comment]
Addressed in https://github.com/NordicMuseum/Wikimedia-Commons-uploads/pull/23

Doesn't break for me right now, as useless as it sounds. You can test it on that branch and see what happens.

**Comment by lokal-profil** [comment]
>after today's updates, Things are now throwing errors in the log instead of crashing the script.
I believe all we did was to log an error and skip these objects rather than raise a (script halting) error.

With the implementation of Thing this should be fine
